# Generated by Django 5.2.4 on 2025-08-04 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('basis', models.CharField(choices=[('territorial', 'Territorial'), ('consumption', 'Consumption-based')], max_length=20)),
                ('value', models.FloatField(help_text='Emissions in metric tonnes CO₂ equivalent')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='emissions.country')),
            ],
            options={
                'ordering': ['country__iso_code', 'year'],
                'unique_together': {('country', 'year', 'basis')},
            },
        ),
    ]
