# Generated by Django 5.2.4 on 2025-08-04 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('population', models.BigIntegerField(help_text='Total population for country-year')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='emissions.country')),
            ],
            options={
                'ordering': ['country__iso_code', 'year'],
                'unique_together': {('country', 'year')},
            },
        ),
    ]
