# Generated by Django 5.2.4 on 2025-08-08 15:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0004_indicator_observation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart',
            options={'ordering': ['-updated']},
        ),
        migrations.RemoveField(
            model_name='chart',
            name='dashboard',
        ),
        migrations.AddField(
            model_name='chart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chart',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
